name: Caller
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
    generate-kip-redirects:
      permissions:
        contents: write
      uses: ./.github/workflows/generate_redirects.yaml
      secrets: inherit
      with: 
        url: https://cwiki.apache.org/confluence/display/kafka/kafka+improvement+proposals
        output_dir: someip-xyz
        prefix: KIP
    generate-flip-redirects:
      permissions:
        contents: write
      uses: ./.github/workflows/generate_redirects.yaml
      secrets: inherit
      with: 
        url: https://cwiki.apache.org/confluence/display/FLINK/Flink+Improvement+Proposals
        output_dir: someip-xyz
        prefix: FLIP
    upload-artifacts:
      needs: [ generate-kip-redirects, generate-flip-redirects ]
      if: needs.generate-kip-redirects.outputs.files_changed == 'true' || needs.generate-flip-redirects.outputs.files_changed == 'true'
      runs-on: ubuntu-latest
      steps:
      - name: Deploy assets to Cloudflare
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy someip-xyz --project-name=someip-xyz
