name: Caller
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'
jobs:
    generate-kip-redirects:
      uses: ./.github/workflows/generate_redirects.yaml
      secrets: inherit
      with: 
        url: https://cwiki.apache.org/confluence/display/kafka/kafka+improvement+proposals
        output_dir: kip
        prefix: KIP
    generate-flip-redirects:
      uses: ./.github/workflows/generate_redirects.yaml
      secrets: inherit
      with: 
        url: https://cwiki.apache.org/confluence/display/FLINK/Flink+Improvement+Proposals
        output_dir: flip
        prefix: FLIP
