name: Generate Redirects

on:
  workflow_call:
    inputs:
      url:
        required: true
        type: string
      output_dir:
        required: true
        type: string
      prefix:
        required: true
        type: string
    outputs:
      files_changed:
       description: "If files have changed"
       value: ${{ jobs.generate.outputs.files_changed }}

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    outputs:
      files_changed: ${{ steps.check_for_changes.outputs.files_changed }}
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
    - name: Generate redirect files
      run: docker run --rm -v ${{ github.workspace }}:/output/ ghcr.io/surdy/proposal-parser:0.0.3 --url ${{ inputs.url }} --output-dir /output/${{ inputs.output_dir }} --prefix ${{inputs.prefix}} 
    - name: Check if any files have changed and commit them
      id: check_for_changes
      run: |
        git config --global user.name "${{ github.actor }}"
        git config --global user.email  "${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com"
        git add ${{ inputs.output_dir }}
        if ! git diff --staged --quiet
        then
          echo "files_changed=true" >> $GITHUB_OUTPUT
          git commit -m "Update ${{inputs.prefix}} redirects"
          git push
        else
          echo "files_changed=false" >> $GITHUB_OUTPUT
        fi
